project_id = "ocydkbblpnshbvkilngl"

[functions.create-payment-intent]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-purchase-email]
verify_jwt = false

[functions.get-secure-download]
verify_jwt = false

[functions.submit-candy-club]
verify_jwt = false

[functions.send-lesson-notification]
verify_jwt = false

[functions.backfill-purchases-ghl]
verify_jwt = false
