const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  arm: (wav, meta, target) => ipcRenderer.invoke('ig:arm', wav, meta, target),
  disarm: (target) => ipcRenderer.invoke('ig:disarm', target),
  openProfile: (handle) => ipcRenderer.invoke('ig:open', handle),
  showInstagram: () => ipcRenderer.invoke('ig:show'),
  grab: () => ipcRenderer.invoke('ig:grab'),
  igDo: (action, handle, target) => ipcRenderer.invoke('ig:do', action, handle, target),
  engage: (handle, airtableId) => ipcRenderer.invoke('ig:engage', handle, airtableId),
  dmInbox: (target) => ipcRenderer.invoke('dm:inbox', target),
  dmThread: (href) => ipcRenderer.invoke('dm:thread', href),
  dmSend: (args) => ipcRenderer.invoke('dm:send', args),
  chatVoice: (target, handle) => ipcRenderer.invoke('dm:chatVoice', target, handle),
  checkLead: (target, handle) => ipcRenderer.invoke('dm:checkLead', target, handle),
  readChat: (target, handle, names) => ipcRenderer.invoke('dm:readChat', target, handle, names),
  chatReport: (target, handle, names) => ipcRenderer.invoke('dm:chatReport', target, handle, names),
  unreadScan: () => ipcRenderer.invoke('dm:unreadScan'),
  inboxReport: () => ipcRenderer.invoke('dm:inboxReport'),
  notify: (m) => ipcRenderer.invoke('notify', m),
  notifyLog: () => ipcRenderer.invoke('notify:log'),
  badge: (n) => ipcRenderer.invoke('app:badge', n),
  keepRunning: (on) => ipcRenderer.invoke('app:keepRunning', on),
  onNav: (cb) => ipcRenderer.on('nav:tab', (_e, m) => cb(m)),
  sendProof: (target, since) => ipcRenderer.invoke('diag:sendProof', target, since),
  watchStart: (target) => ipcRenderer.invoke('diag:watchStart', target),
  watchStop: (target) => ipcRenderer.invoke('diag:watchStop', target),
  describeTab: (target) => ipcRenderer.invoke('diag:describe', target),
  snap: (target, name, report) => ipcRenderer.invoke('diag:snap', target, name, report),
  revealShot: (file) => ipcRenderer.invoke('diag:reveal', file),
  replyDraft: (key, prompt) => ipcRenderer.invoke('reply:draft', key, prompt),
  replyTest: (key) => ipcRenderer.invoke('reply:test', key),
  torreyInvite: (cfg, args) => ipcRenderer.invoke('torrey:invite', cfg, args),
  torreyTest: (cfg) => ipcRenderer.invoke('torrey:test', cfg),
  copyText: (text) => ipcRenderer.invoke('clipboard:text', text),
  patchAirtable: (at, id, fields) => ipcRenderer.invoke('airtable:patch', at, id, fields),
  removeAirtable: (at, id, opts) => ipcRenderer.invoke('airtable:remove', at, id, opts),
  onStatus: (cb) => ipcRenderer.on('ig:status', (_e, m) => cb(m)),
  saveClip: (wav, name) => ipcRenderer.invoke('clip:save', wav, name),
  reveal: (file) => ipcRenderer.invoke('clip:reveal', file),
  pullAirtable: (at) => ipcRenderer.invoke('airtable:pull', at),
  pullSentAirtable: (at) => ipcRenderer.invoke('airtable:pullSent', at),
  markSent: (at, id) => ipcRenderer.invoke('airtable:sent', at, id),
  speak: (text, settings) => ipcRenderer.invoke('tts', text, settings),
  showPane: (which) => ipcRenderer.invoke('pane:show', which),
  followConfig: (at) => ipcRenderer.invoke('follow:config', at),
  followSet: (on) => ipcRenderer.invoke('follow:set', on),
  followState: () => ipcRenderer.invoke('follow:state'),
  followProbe: (handle) => ipcRenderer.invoke('follow:probe', handle),
  followEngageNow: (handle, airtableId) => ipcRenderer.invoke('follow:engageNow', handle, airtableId),
  voiceTimes: (times) => ipcRenderer.invoke('follow:voiceTimes', times),
  testFast: () => ipcRenderer.invoke('app:testFast'),
  onFollow: (cb) => ipcRenderer.on('follow:status', (_e, s) => cb(s)),
  onFollowed: (cb) => ipcRenderer.on('follow:followed', (_e, m) => cb(m)),
  findConfig: (cfg) => ipcRenderer.invoke('find:config', cfg),
  findSet: (on) => ipcRenderer.invoke('find:set', on),
  findState: () => ipcRenderer.invoke('find:state'),
  findVerdicts: (handles) => ipcRenderer.invoke('find:verdicts', handles),
  findTest: (tag) => ipcRenderer.invoke('find:test', tag),
  onFind: (cb) => ipcRenderer.on('find:status', (_e, s) => cb(s)),
});
