-- Insert all products with their download URLs from LEC bucket
INSERT INTO products (title, price, original_price, image, category, bpm, key, short_description, full_description, features, download_url, is_on_sale) VALUES
('27 OTT Rack', 'Free', NULL, '/lovable-uploads/27-ott-rack.png', 'Live Racks', NULL, NULL, 
 '27 OTTs for crazy glitch and bass sound design',
 'This Ableton specific rack is a series of 27 OTTs for crazy glitch and bass sound design. Perfect for experimental producers looking to push sonic boundaries and create unique textures.',
 ARRAY['27 unique OTT configurations', 'Optimized for glitch effects', 'Perfect for bass sound design', 'Ableton Live rack format', 'Instant download'],
 'https://ocydkbblpnshbvkilngl.supabase.co/storage/v1/object/public/LEC/27 OTT RACK.adg',
 false),

('Serum 2 Randomizer Rack', '$5.00', NULL, '/lovable-uploads/randomizer-rack.png', 'Live Racks', NULL, NULL,
 'Randomize and discover unique sounds with Serum 2',
 'This powerful Ableton rack allows you to randomize parameters in Serum 2 for instant inspiration and unique sound design possibilities. Perfect for discovering new sonic territories!',
 ARRAY['Intelligent parameter randomization', 'Save your favorite random patches', 'Works with Serum 2', 'Ableton Live rack format', 'Video tutorial included'],
 'https://ocydkbblpnshbvkilngl.supabase.co/storage/v1/object/public/LEC/Serum 2 Randomize Rack.adg',
 false),

('Hip Hop Sample Pack', 'Free', NULL, '/lovable-uploads/hip-hop-trap-starter-pack.png', 'Sample Pack', NULL, NULL,
 'Essential hip hop samples for modern trap and hip hop production',
 'Over 100 samples ideal for producing hip hop, boom bap, trap or any other sub-genre of rap. This sample pack includes: Kicks, Snares, Percussive elements, Hi-Hats, FX, Synths, Plucks, 808s & More!',
 ARRAY['100+ samples', 'Kicks, Snares & Hi-Hats', '808s & Synths', 'FX & Plucks', 'Royalty-free WAV format'],
 'https://ocydkbblpnshbvkilngl.supabase.co/storage/v1/object/public/LEC/Hip Hop & Trap Starter Kit.zip',
 false),

('Deep House Ableton Project File', 'Free', NULL, '/lovable-uploads/deep-house-ableton-project-new.png', 'Sample Pack', NULL, NULL,
 'Complete deep house project from our popular YouTube tutorial',
 'This is the full Ableton project file from our deep house tutorial on YouTube. Includes all MIDI, audio samples, and effect chains so you can learn our complete production process!',
 ARRAY['Full Ableton project file', 'All samples included', 'MIDI files included', 'Mix-ready arrangement', 'YouTube tutorial link'],
 'https://ocydkbblpnshbvkilngl.supabase.co/storage/v1/object/public/LEC/Deep House Project.alp',
 false),

('1 Knob Build', 'Free', NULL, '/lovable-uploads/1-knob-build.png', 'Live Racks', NULL, NULL,
 'Simplify complex effects chains with one-knob control',
 'This innovative Ableton rack lets you control complex effect chains with a single knob. Perfect for live performances and quick creative adjustments. Simplify your workflow!',
 ARRAY['One-knob control system', 'Multiple effect chains', 'Performance-ready', 'Easy to customize', 'Tutorial included'],
 'https://ocydkbblpnshbvkilngl.supabase.co/storage/v1/object/public/LEC/1 KNOB BUILD.adg',
 false),

('Bohemyth''s 1st Sample Pack', 'Free', NULL, '/lovable-uploads/bohemyth-1st-sample-pack.png', 'Sample Pack', NULL, NULL,
 'Welcome! Please Enjoy my new sample pack.',
 'Bohemyth''s 1st Sample Pack - Welcome! Please Enjoy my new sample pack. This collection contains some of my favorite samples throughout the last few years and from some of my favorite projects. Enjoy!',
 ARRAY['Curated favorite samples', 'Years of production gems', '100% Royalty-free', 'WAV format', 'Instant download'],
 'https://ocydkbblpnshbvkilngl.supabase.co/storage/v1/object/public/LEC/Bohemyth Sample Pack.zip',
 false),

('Bohemyth''s Serum (1) Rack', 'Free', NULL, '/lovable-uploads/bohemyth-serum-rack.png', 'Live Racks', NULL, NULL,
 'Advanced Serum wavetable control rack for Ableton Live',
 'This powerful Ableton rack gives you intuitive control over Serum''s wavetable parameters including timbre, speed, hyper, warp, and wavetable position controls. Perfect for creating evolving textures and dynamic sound design!',
 ARRAY['6 macro controls', 'Timbre & Speed control', 'Warp parameters', 'Wavetable position control', 'Ableton Live rack format'],
 'https://ocydkbblpnshbvkilngl.supabase.co/storage/v1/object/public/LEC/Bohemyth Serum Rack.adg',
 false),

('Ableton Quick Commands Cheat Sheet', 'Free', NULL, '/lovable-uploads/ableton-quick-commands.png', 'Sample Pack', NULL, NULL,
 'Essential keyboard shortcuts for Ableton Live',
 'A comprehensive cheat sheet of the most useful Ableton Live keyboard shortcuts and quick commands. Speed up your workflow and produce faster!',
 ARRAY['All essential shortcuts', 'Workflow optimization', 'Printable PDF format', 'Beginner friendly', 'Instant download'],
 'https://ocydkbblpnshbvkilngl.supabase.co/storage/v1/object/public/LEC/Ableton Quick Commands.pdf',
 false),

('Hat Sauce', 'Free', NULL, '/lovable-uploads/hat-sauce-rack.png', 'Live Racks', NULL, NULL,
 'Transform your hi-hats with unique processing',
 'This Ableton rack adds flavor and character to your hi-hat patterns with creative processing chains designed for modern electronic music production.',
 ARRAY['Creative hi-hat processing', 'Multiple effect chains', 'One-knob simplicity', 'Ableton Live rack', 'Instant download'],
 'https://ocydkbblpnshbvkilngl.supabase.co/storage/v1/object/public/LEC/HAT SAUCE.adg',
 false),

('HAAS Effect', 'Free', NULL, '/lovable-uploads/haas-effect-rack.png', 'Live Racks', NULL, NULL,
 'Professional stereo widening with HAAS effect',
 'Create wide stereo imaging using the HAAS effect technique. This rack provides easy control over stereo width while maintaining mono compatibility.',
 ARRAY['True HAAS effect processing', 'Mono compatible', 'Width control', 'Ableton Live rack', 'Instant download'],
 'https://ocydkbblpnshbvkilngl.supabase.co/storage/v1/object/public/LEC/Hubert Haas Effect.adg',
 false),

('Vocal Clean Up Rack', 'Free', NULL, '/lovable-uploads/vocal-clean-rack.png', 'Live Racks', NULL, NULL,
 'Professional vocal cleaning and preparation',
 'Clean up your vocal recordings with this comprehensive Ableton rack. Remove noise, control dynamics, and prepare vocals for further processing.',
 ARRAY['Noise reduction', 'Dynamic control', 'EQ cleanup', 'Ableton Live rack', 'Instant download'],
 'https://ocydkbblpnshbvkilngl.supabase.co/storage/v1/object/public/LEC/Vocal Clean Up Rack.adg',
 false),

('Vocal Sauce', 'Free', NULL, '/lovable-uploads/vocal-sauce-rack.png', 'Live Racks', NULL, NULL,
 'Add character and polish to your vocals',
 'Transform your vocals with creative effects and professional polish. This rack provides everything you need for radio-ready vocal production.',
 ARRAY['Creative vocal effects', 'Professional polish', 'Easy to use', 'Ableton Live rack', 'Instant download'],
 'https://ocydkbblpnshbvkilngl.supabase.co/storage/v1/object/public/LEC/Vocal Sauce.adg',
 false);